name: Run Benchmark with specific binary
on:
  workflow_dispatch:
    inputs:
      benchmark:
        description: 'Benchmark to run (e.g. any benchmark as in regression/<benchmark>)'
        required: true
        default: 'esbmc-cpp/cpp'
      binary:
        description: 'ESBMC binary'
        required: true
        default: 'esbmc_binary/latest_master/esbmc'
      mode:
        description: 'Mode'
        required: true
        default: 'CORE'
      library:
        description: 'C++ OM lib (leave blank for new ESBMC binary)'
        required: false
        default: '-l ./libraries'

jobs:
  build-linux:
    strategy:
      matrix:
        os: [ubuntu-latest]
    name: Build ESBMC (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90 # 1.5h
    steps:
      - name: Confirm the benchmark
        run: echo ${{ github.event.inputs.benchmark }}
      - name: Confirm the binary
        run: echo ${{ github.event.inputs.binary }}
      - name: Confirm the mode
        run: echo ${{ github.event.inputs.mode }}
      - name: Run benchmark with the given binary
        continue-on-error: true
        env:
          ESBMC_OPTS: ${{ inputs.options }}
        run: ./run.sh -r ${{ inputs.benchmark }} -t ${{ inputs.binary }} -m ${{ inputs.mode }} ${{ inputs.library }}
